INSERT INTO modules (id, name, surname, birthdate, type) VALUES (1, 'Jason', 'Smith', '2000-01-01', 'OWNER');
INSERT INTO modules (id, name, surname, birthdate, type) VALUES (2, 'Alice', 'Anderson', '1990-01-01', 'CHILD');
INSERT INTO modules (id, name, surname, birthdate, type) VALUES (3, 'Bob', 'Anderson', '1980-02-02','SPOUSE');
INSERT INTO modules (id, name, surname, birthdate, type) VALUES (4, 'Bob', 'Carlsen', '1980-03-03','SPOUSE');
INSERT INTO modules (id, name, surname, birthdate, type) VALUES (5, 'Dean', 'Dobro', '2000-04-04','CHILD');
INSERT INTO modules (id, name, surname, birthdate, type) VALUES (6, 'Ester', 'Effenbach', '2010-04-05','OWNER');
INSERT INTO modules (id, name, surname, birthdate, type) VALUES (7, 'Filip', 'Fjord', '1950-06-06','SPOUSE');
INSERT INTO modules (id, name, surname, birthdate, type) VALUES (8, 'Greta', 'Gunderson', '1960-07-07','CHILD');
INSERT INTO modules (id, name, surname, birthdate, type) VALUES (9, 'Hans', 'Haskell', '1975-08-08','OWNER');
INSERT INTO modules (id, name, surname, birthdate, type) VALUES (10, 'Bob', 'Anderson', '1985-09-09','SPOUSE');